[package]
name = "minigrep"
version = "0.1.0"
description = "A inferior version of grep written in rust. Learn how to use clap and parse positional arguments."
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
